const countryData = {
    'india': ['Mumbai', 'New Delhi', 'Bangalore', 'Chennai', 'Kolkata', 'Jaipur', 'Hyderabad', 'Goa', 'Agra', 'Varanasi'],
    'united states': ['New York', 'Los Angeles', 'Chicago', 'Las Vegas', 'San Francisco', 'Miami', 'Washington D.C.', 'New Orleans', 'Seattle', 'Honolulu'],
    'italy': ['Rome', 'Florence', 'Venice', 'Milan', 'Naples', 'Pisa', 'Bologna', 'Verona', 'Turin', 'Genoa'],
    'france': ['Paris', 'Nice', 'Marseille', 'Lyon', 'Toulouse', 'Bordeaux', 'Lille', 'Strasbourg', 'Nantes', 'Cannes'],
    'japan': ['Tokyo', 'Kyoto', 'Osaka', 'Sapporo', 'Hiroshima', 'Fukuoka', 'Nara', 'Kobe', 'Yokohama', 'Nagoya'],
    'united kingdom': ['London', 'Edinburgh', 'Manchester', 'Liverpool', 'Glasgow', 'Bristol', 'Oxford', 'Cambridge', 'Birmingham', 'Belfast'],
    'germany': ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Düsseldorf', 'Stuttgart', 'Leipzig', 'Dresden', 'Nuremberg'],
    'australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Cairns', 'Canberra', 'Hobart', 'Darwin'],
    'brazil': ['Rio de Janeiro', 'São Paulo', 'Salvador', 'Fortaleza', 'Brasília', 'Manaus', 'Curitiba', 'Recife', 'Belo Horizonte', 'Foz do Iguaçu'],
    'canada': ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Quebec City', 'Banff', 'Edmonton', 'Victoria', 'Halifax'],
    'china': ['Beijing', 'Shanghai', 'Hong Kong', 'Xi an', 'Chengdu', 'Guilin', 'Hangzhou', 'Suzhou', 'Lhasa', 'Macau'],
    'egypt': ['Cairo', 'Luxor', 'Aswan', 'Giza', 'Sharm El Sheikh', 'Alexandria', 'Hurghada', 'Dahab', 'Siwa Oasis', 'Port Said'],
    'spain': ['Madrid', 'Barcelona', 'Seville', 'Granada', 'Valencia', 'Ibiza', 'Mallorca', 'Cordoba', 'Bilbao', 'Toledo'],
    'pakistan': ['Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 'Rawalpindi', 'Peshawar', 'Multan', 'Quetta', 'Hunza Valley', 'Skardu'],
    'iran': ['Tehran', 'Isfahan', 'Shiraz', 'Yazd', 'Kashan', 'Tabriz', 'Kerman', 'Mashhad', 'Qeshm', 'Ahvaz'],
    'switzerland': ['Zurich', 'Geneva', 'Lucerne', 'Interlaken', 'Bern', 'Zermatt', 'Lausanne', 'Basel', 'St. Moritz', 'Lugano'],
    'netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Maastricht', 'Groningen', 'Delft', 'Leiden', 'Haarlem'],
    'greece': ['Athens', 'Santorini', 'Mykonos', 'Crete', 'Rhodes', 'Corfu', 'Thessaloniki', 'Zakynthos', 'Naxos', 'Paros'],
    'ireland': ['Dublin', 'Galway', 'Cork', 'Killarney', 'Limerick', 'Kilkenny', 'Waterford', 'Sligo', 'Westport', 'Dingle'],
    'south korea': ['Seoul', 'Busan', 'Jeju Island', 'Incheon', 'Gyeongju', 'Daegu', 'Daejeon', 'Suwon', 'Jeonju', 'Gwangju'],
    'thailand': ['Bangkok', 'Phuket', 'Chiang Mai', 'Pattaya', 'Krabi', 'Koh Samui', 'Ayutthaya', 'Hua Hin', 'Pai', 'Kanchanaburi'],
    'vietnam': ['Hanoi', 'Ho Chi Minh City', 'Ha Long Bay', 'Hoi An', 'Da Nang', 'Nha Trang', 'Hue', 'Sapa', 'Mui Ne', 'Phu Quoc'],
    'mexico': ['Mexico City', 'Cancun', 'Tulum', 'Playa del Carmen', 'Cabo San Lucas', 'Oaxaca', 'Guadalajara', 'Puerto Vallarta', 'San Miguel de Allende', 'Merida'],
    'argentina': ['Buenos Aires', 'Bariloche', 'Mendoza', 'Ushuaia', 'Iguazu Falls', 'El Calafate', 'Salta', 'Cordoba', 'Mar del Plata', 'Rosario'],
    'new zealand': ['Auckland', 'Queenstown', 'Christchurch', 'Wellington', 'Rotorua', 'Dunedin', 'Tauranga', 'Nelson', 'Napier', 'Wanaka'],
    'russia': ['Moscow', 'Saint Petersburg', 'Kazan', 'Sochi', 'Vladivostok', 'Yekaterinburg', 'Novosibirsk', 'Nizhny Novgorod', 'Samara', 'Rostov-on-Don'],
    'turkey': ['Istanbul', 'Ankara', 'Antalya', 'Izmir', 'Göreme (Cappadocia)', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Trabzon'],
    'portugal': ['Lisbon', 'Porto', 'Sintra', 'Lagos', 'Albufeira', 'Funchal', 'Coimbra', 'Braga', 'Evora', 'Aveiro'],
    'sweden': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Lund', 'Helsingborg', 'Kiruna', 'Visby', 'Umeå', 'Linköping'],
    'austria': ['Vienna', 'Salzburg', 'Innsbruck', 'Hallstatt', 'Graz', 'Linz', 'Zell am See', 'Klagenfurt', 'Bregenz', 'Eisenstadt'],
    'poland': ['Warsaw', 'Kraków', 'Gdańsk', 'Wrocław', 'Poznań', 'Zakopane', 'Szczecin', 'Łódź', 'Katowice', 'Lublin'],
    'indonesia': ['Bali (Denpasar)', 'Jakarta', 'Yogyakarta', 'Ubud', 'Bandung', 'Surabaya', 'Medan', 'Lombok', 'Semarang', 'Makassar'],
    'malaysia': ['Kuala Lumpur', 'Penang', 'Langkawi', 'Malacca', 'Johor Bahru', 'Kota Kinabalu', 'Ipoh', 'Cameron Highlands', 'Kuching', 'Genting Highlands'],
    'peru': ['Lima', 'Cusco', 'Machu Picchu (Aguas Calientes)', 'Arequipa', 'Iquitos', 'Puno', 'Trujillo', 'Mancora', 'Huaraz', 'Paracas'],
    'morocco': ['Marrakesh', 'Fes', 'Casablanca', 'Chefchaouen', 'Rabat', 'Tangier', 'Agadir', 'Meknes', 'Ouarzazate', 'Essaouira'],
    'south africa': ['Cape Town', 'Johannesburg', 'Durban', 'Pretoria', 'Port Elizabeth', 'Skukuza (Kruger Park)', 'Stellenbosch', 'Bloemfontein', 'Knysna', 'Hermanus'],
    'colombia': ['Bogotá', 'Medellín', 'Cartagena', 'Cali', 'Santa Marta', 'Salento', 'Guatapé', 'Barranquilla', 'San Andrés', 'Leticia'],
    'belgium': ['Brussels', 'Bruges', 'Ghent', 'Antwerp', 'Leuven', 'Dinant', 'Liege', 'Namur', 'Mechelen', 'Ypres'],
    'denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Billund', 'Skagen', 'Roskilde', 'Helsingør', 'Ribe', 'Esbjerg'],
    'philippines': ['Manila', 'Cebu City', 'Boracay', 'El Nido', 'Coron', 'Baguio', 'Davao City', 'Vigan', 'Siargao', 'Bohol']
};